# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-14 10:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bahan',
            fields=[
                ('id_bahan', models.CharField(db_column='ID_BAHAN', max_length=10, primary_key=True, serialize=False)),
                ('harga_bahan', models.IntegerField(db_column='HARGA_BAHAN')),
                ('jumlah_bahan', models.IntegerField(db_column='JUMLAH_BAHAN')),
                ('nama_bahan', models.CharField(db_column='NAMA_BAHAN', max_length=20)),
            ],
            options={
                'managed': False,
                'db_table': 'bahan',
            },
        ),
        migrations.CreateModel(
            name='HistoryPemesanan',
            fields=[
                ('tanggal_pemesanan', models.DateTimeField(db_column='TANGGAL_PEMESANAN', primary_key=True, serialize=False)),
            ],
            options={
                'managed': False,
                'db_table': 'history_pemesanan',
            },
        ),
        migrations.CreateModel(
            name='Makanan',
            fields=[
                ('id_makanan', models.CharField(db_column='ID_MAKANAN', max_length=10, primary_key=True, serialize=False)),
                ('nama_makanan', models.CharField(db_column='NAMA_MAKANAN', max_length=15)),
                ('rating', models.IntegerField(db_column='RATING')),
                ('energi', models.CharField(db_column='ENERGI', max_length=10)),
                ('protein', models.CharField(db_column='PROTEIN', max_length=10)),
                ('deskripsi', models.CharField(db_column='DESKRIPSI', max_length=100)),
                ('stok_makanan', models.IntegerField(db_column='STOK_MAKANAN')),
                ('lemak', models.CharField(db_column='LEMAK', max_length=10)),
            ],
            options={
                'managed': False,
                'db_table': 'makanan',
            },
        ),
        migrations.CreateModel(
            name='Pelanggan',
            fields=[
                ('id_pelanggan', models.CharField(db_column='ID_PELANGGAN', max_length=10, primary_key=True, serialize=False)),
                ('nama', models.CharField(db_column='NAMA', max_length=25)),
                ('alamat', models.CharField(db_column='ALAMAT', max_length=50)),
                ('email', models.CharField(db_column='EMAIL', max_length=30)),
                ('password', models.CharField(db_column='PASSWORD', max_length=25)),
                ('no_hp', models.IntegerField(blank=True, db_column='NO_HP', null=True)),
                ('total_poin', models.IntegerField(db_column='TOTAL_POIN')),
            ],
            options={
                'managed': False,
                'db_table': 'pelanggan',
            },
        ),
        migrations.CreateModel(
            name='Pembayaran',
            fields=[
                ('id_pembayaran', models.CharField(db_column='ID_PEMBAYARAN', max_length=10, primary_key=True, serialize=False)),
                ('status_pembayaran', models.IntegerField(db_column='STATUS_PEMBAYARAN')),
            ],
            options={
                'managed': False,
                'db_table': 'pembayaran',
            },
        ),
        migrations.CreateModel(
            name='PembelianPoin',
            fields=[
                ('jumlah_pembelian_poin', models.IntegerField(db_column='JUMLAH_PEMBELIAN_POIN')),
                ('tanggal_pembelian', models.DateTimeField(db_column='TANGGAL_PEMBELIAN', primary_key=True, serialize=False)),
            ],
            options={
                'managed': False,
                'db_table': 'pembelian_poin',
            },
        ),
        migrations.CreateModel(
            name='Pemesanan',
            fields=[
                ('id_pesanan', models.CharField(db_column='ID_PESANAN', max_length=10, primary_key=True, serialize=False)),
                ('jumlah_pesanan', models.IntegerField(db_column='JUMLAH_PESANAN')),
                ('tanggal_pengiriman', models.DateTimeField(db_column='TANGGAL_PENGIRIMAN')),
            ],
            options={
                'managed': False,
                'db_table': 'pemesanan',
            },
        ),
        migrations.CreateModel(
            name='Poin',
            fields=[
                ('id_poin', models.CharField(db_column='ID_POIN', max_length=10, primary_key=True, serialize=False)),
                ('harga_poin', models.IntegerField(db_column='HARGA_POIN')),
            ],
            options={
                'managed': False,
                'db_table': 'poin',
            },
        ),
        migrations.CreateModel(
            name='Tracking',
            fields=[
                ('id_tracking', models.CharField(db_column='ID_TRACKING', max_length=10, primary_key=True, serialize=False)),
                ('status_tracking', models.IntegerField(db_column='STATUS_TRACKING')),
            ],
            options={
                'managed': False,
                'db_table': 'tracking',
            },
        ),
        migrations.CreateModel(
            name='Komposisi',
            fields=[
                ('id_bahan', models.ForeignKey(db_column='ID_BAHAN', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='alakadarapp.Bahan')),
            ],
            options={
                'managed': False,
                'db_table': 'komposisi',
            },
        ),
        migrations.CreateModel(
            name='MakananSiapCatering',
            fields=[
                ('id_makanan', models.ForeignKey(db_column='ID_MAKANAN', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='alakadarapp.Makanan')),
                ('nama_makanan', models.CharField(db_column='NAMA_MAKANAN', max_length=15)),
                ('rating', models.IntegerField(db_column='RATING')),
                ('energi', models.CharField(db_column='ENERGI', max_length=10)),
                ('protein', models.CharField(db_column='PROTEIN', max_length=10)),
                ('deskripsi', models.CharField(db_column='DESKRIPSI', max_length=100)),
                ('stok_makanan', models.IntegerField(db_column='STOK_MAKANAN')),
                ('lemak', models.CharField(db_column='LEMAK', max_length=10)),
                ('poin', models.IntegerField(db_column='POIN')),
            ],
            options={
                'managed': False,
                'db_table': 'makanan_siap_catering',
            },
        ),
        migrations.CreateModel(
            name='MakananSiapMakan',
            fields=[
                ('id_makanan', models.ForeignKey(db_column='ID_MAKANAN', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='alakadarapp.Makanan')),
                ('nama_makanan', models.CharField(db_column='NAMA_MAKANAN', max_length=15)),
                ('rating', models.IntegerField(db_column='RATING')),
                ('energi', models.CharField(db_column='ENERGI', max_length=10)),
                ('protein', models.CharField(db_column='PROTEIN', max_length=10)),
                ('deskripsi', models.CharField(db_column='DESKRIPSI', max_length=100)),
                ('stok_makanan', models.IntegerField(db_column='STOK_MAKANAN')),
                ('lemak', models.CharField(db_column='LEMAK', max_length=10)),
                ('harga', models.IntegerField(db_column='HARGA')),
            ],
            options={
                'managed': False,
                'db_table': 'makanan_siap_makan',
            },
        ),
        migrations.CreateModel(
            name='SiapCatering',
            fields=[
                ('id_pesanan', models.ForeignKey(db_column='ID_PESANAN', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='alakadarapp.Pemesanan')),
                ('id_pelanggan', models.CharField(blank=True, db_column='ID_PELANGGAN', max_length=10, null=True)),
                ('id_makanan', models.CharField(blank=True, db_column='ID_MAKANAN', max_length=10, null=True)),
                ('jumlah_pesanan', models.IntegerField(db_column='JUMLAH_PESANAN')),
                ('tanggal_pengiriman', models.DateTimeField(db_column='TANGGAL_PENGIRIMAN')),
                ('total_poin', models.IntegerField(db_column='TOTAL_POIN')),
            ],
            options={
                'managed': False,
                'db_table': 'siap_catering',
            },
        ),
        migrations.CreateModel(
            name='SiapMakan',
            fields=[
                ('id_pesanan', models.ForeignKey(db_column='ID_PESANAN', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='alakadarapp.Pemesanan')),
                ('id_pelanggan', models.CharField(blank=True, db_column='ID_PELANGGAN', max_length=10, null=True)),
                ('id_makanan', models.CharField(blank=True, db_column='ID_MAKANAN', max_length=10, null=True)),
                ('jumlah_pesanan', models.IntegerField(db_column='JUMLAH_PESANAN')),
                ('tanggal_pengiriman', models.DateTimeField(db_column='TANGGAL_PENGIRIMAN')),
                ('total_harga', models.IntegerField(db_column='TOTAL_HARGA')),
            ],
            options={
                'managed': False,
                'db_table': 'siap_makan',
            },
        ),
        migrations.CreateModel(
            name='SiapMasak',
            fields=[
                ('id_pesanan', models.ForeignKey(db_column='ID_PESANAN', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='alakadarapp.Pemesanan')),
                ('id_pelanggan', models.CharField(blank=True, db_column='ID_PELANGGAN', max_length=10, null=True)),
                ('id_makanan', models.CharField(blank=True, db_column='ID_MAKANAN', max_length=10, null=True)),
                ('jumlah_pesanan', models.IntegerField(db_column='JUMLAH_PESANAN')),
                ('tanggal_pengiriman', models.DateTimeField(db_column='TANGGAL_PENGIRIMAN')),
                ('total_harga', models.IntegerField(db_column='TOTAL_HARGA')),
            ],
            options={
                'managed': False,
                'db_table': 'siap_masak',
            },
        ),
        migrations.CreateModel(
            name='Bento',
            fields=[
                ('id_makanan', models.ForeignKey(db_column='ID_MAKANAN', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='alakadarapp.MakananSiapMakan')),
                ('nama_makanan', models.CharField(db_column='NAMA_MAKANAN', max_length=15)),
                ('rating', models.IntegerField(db_column='RATING')),
                ('energi', models.CharField(db_column='ENERGI', max_length=10)),
                ('protein', models.CharField(db_column='PROTEIN', max_length=10)),
                ('deskripsi', models.CharField(db_column='DESKRIPSI', max_length=100)),
                ('stok_makanan', models.IntegerField(db_column='STOK_MAKANAN')),
                ('lemak', models.CharField(db_column='LEMAK', max_length=10)),
                ('harga', models.IntegerField(db_column='HARGA')),
            ],
            options={
                'managed': False,
                'db_table': 'bento',
            },
        ),
        migrations.CreateModel(
            name='SiapSaji',
            fields=[
                ('id_makanan', models.ForeignKey(db_column='ID_MAKANAN', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='alakadarapp.MakananSiapMakan')),
                ('nama_makanan', models.CharField(db_column='NAMA_MAKANAN', max_length=15)),
                ('rating', models.IntegerField(db_column='RATING')),
                ('energi', models.CharField(db_column='ENERGI', max_length=10)),
                ('protein', models.CharField(db_column='PROTEIN', max_length=10)),
                ('deskripsi', models.CharField(db_column='DESKRIPSI', max_length=100)),
                ('stok_makanan', models.IntegerField(db_column='STOK_MAKANAN')),
                ('lemak', models.CharField(db_column='LEMAK', max_length=10)),
                ('harga', models.IntegerField(db_column='HARGA')),
            ],
            options={
                'managed': False,
                'db_table': 'siap_saji',
            },
        ),
    ]
